/**
 * Generate `e2e/COVERAGE.md` — the traceability map from requirements/findings to
 * the journeys that exercise them (e2e plan Phase 8 §3).
 *
 * The map is DERIVED from the specs so it cannot rot:
 *   - journey ids come from each `test.describe('J…')` title,
 *   - tags come from the describe's `{ tag: [...] }`,
 *   - requirements and findings come from `// @coverage @req(R6.3)` /
 *     `@finding(P7-a)` annotation comments in the spec files.
 *
 * Run: `npm run coverage:map` (writes e2e/COVERAGE.md).
 * Pass `--check` to fail (exit 1) if the committed COVERAGE.md is stale — used by
 * CI so the map is regenerated whenever a spec's coverage annotations change.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');
const JOURNEYS = join(ROOT, 'e2e', 'journeys');
const OUT = join(ROOT, 'e2e', 'COVERAGE.md');

interface SpecInfo {
	file: string; // repo-relative
	phase: string;
	journeys: string[];
	tags: string[];
	reqs: string[];
	findings: string[];
}

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const name of readdirSync(dir)) {
		const p = join(dir, name);
		if (statSync(p).isDirectory()) out.push(...walk(p));
		else if (p.endsWith('.spec.ts')) out.push(p);
	}
	return out;
}

function uniqSort(xs: string[]): string[] {
	return [...new Set(xs)].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

/** Every `@req(X)` / `@finding(Y)` token anywhere in the file. */
function annotations(src: string, kind: 'req' | 'finding'): string[] {
	const re = new RegExp(`@${kind}\\(([^)]+)\\)`, 'g');
	const out: string[] = [];
	let m: RegExpExecArray | null;
	while ((m = re.exec(src))) out.push(m[1].trim());
	return out;
}

/** Journey ids (J1.1, J7.6, …) and the tag arrays from each describe title. */
function describeInfo(src: string): { journeys: string[]; tags: string[] } {
	const journeys: string[] = [];
	const tags: string[] = [];
	// describe titles
	const titleRe = /describe\(\s*['"`]([^'"`]+)['"`]/g;
	let m: RegExpExecArray | null;
	while ((m = titleRe.exec(src))) {
		const ids = m[1].match(/J\d+(?:\.\d+)?/g);
		if (ids) journeys.push(...ids);
	}
	// tag arrays: tag: ['@smoke', '@stage2']
	const tagRe = /tag:\s*\[([^\]]*)\]/g;
	while ((m = tagRe.exec(src))) {
		for (const t of m[1].match(/@[\w-]+/g) ?? []) tags.push(t);
	}
	return { journeys: uniqSort(journeys), tags: uniqSort(tags) };
}

function focusedOrSkipped(src: string): string[] {
	const bad: string[] = [];
	for (const pat of ['test.only', 'describe.only', 'test.skip', 'test.fixme', '.only(']) {
		if (src.includes(pat)) bad.push(pat);
	}
	return bad;
}

const specs: SpecInfo[] = [];
const guardHits: string[] = [];

// Only the canonical phased journeys (`e2e/journeys/phase-*/`). Any pre-plan
// legacy specs still sitting directly under e2e/journeys/ are excluded from the
// map — they are slated for retirement (Phase 8 §5).
for (const abs of walk(JOURNEYS)
	.filter((p) => /[/\\]phase-\d+[/\\]/.test(p))
	.sort()) {
	const src = readFileSync(abs, 'utf8');
	const file = relative(ROOT, abs);
	const phase = (file.match(/phase-(\d+)/)?.[1] ?? '?').padStart(1, '0');
	const { journeys, tags } = describeInfo(src);
	const bad = focusedOrSkipped(src);
	if (bad.length) guardHits.push(`${file}: ${bad.join(', ')}`);
	specs.push({
		file,
		phase,
		journeys,
		tags,
		reqs: uniqSort(annotations(src, 'req')),
		findings: uniqSort(annotations(src, 'finding'))
	});
}

// ---- Build inverted maps -------------------------------------------------
const journeyToSpec = new Map<string, string>();
const reqToJourneys = new Map<string, Set<string>>();
const findingToJourneys = new Map<string, Set<string>>();
const tagCounts = new Map<string, number>();
const allJourneys = new Set<string>();

for (const s of specs) {
	for (const j of s.journeys) {
		allJourneys.add(j);
		if (!journeyToSpec.has(j)) journeyToSpec.set(j, s.file);
	}
	for (const t of s.tags) tagCounts.set(t, (tagCounts.get(t) ?? 0) + 1);
	const label = s.journeys.length ? s.journeys.join(', ') : s.file.split('/').pop()!;
	for (const r of s.reqs)
		(reqToJourneys.get(r) ?? reqToJourneys.set(r, new Set()).get(r)!).add(label);
	for (const f of s.findings)
		(findingToJourneys.get(f) ?? findingToJourneys.set(f, new Set()).get(f)!).add(label);
}

// ---- Render --------------------------------------------------------------
const lines: string[] = [];
lines.push('# E2E coverage map');
lines.push('');
lines.push(
	'<!-- GENERATED by `npm run coverage:map` (e2e/scripts/generate-coverage.ts). Do not edit by hand. -->'
);
lines.push('');
lines.push('Traceability from product requirements (`R*`/`G*`) and review findings/decisions');
lines.push('(`P-*`, `F-*`, `D*`) to the journeys that exercise them. Derived from the specs:');
lines.push('journey ids from `describe` titles, tags from their `tag:` arrays, and requirements/');
lines.push('findings from `// @coverage @req(...)` / `@finding(...)` annotations.');
lines.push('');

const phases = uniqSort(specs.map((s) => s.phase));
lines.push('## Summary');
lines.push('');
lines.push(`- Spec files: **${specs.length}** across ${phases.length} phases`);
lines.push(`- Journeys: **${allJourneys.size}**`);
lines.push(
	`- Requirements mapped: **${reqToJourneys.size}**; findings/decisions mapped: **${findingToJourneys.size}**`
);
lines.push(
	`- Tags: ${uniqSort([...tagCounts.keys()])
		.map((t) => `\`${t}\` ×${tagCounts.get(t)}`)
		.join(', ')}`
);
lines.push('');

lines.push('## Journeys by phase');
lines.push('');
lines.push('| Phase | Journey(s) | Spec | Tags | Requirements | Findings/decisions |');
lines.push('| ----- | ---------- | ---- | ---- | ------------ | ------------------ |');
for (const s of specs) {
	lines.push(
		`| ${s.phase} | ${s.journeys.join(', ') || '—'} | \`${s.file.replace('e2e/journeys/', '')}\` | ${
			s.tags.map((t) => t).join(' ') || '—'
		} | ${s.reqs.join(', ') || '—'} | ${s.findings.join(', ') || '—'} |`
	);
}
lines.push('');

lines.push('## Requirement → journeys');
lines.push('');
lines.push('| Requirement | Journeys |');
lines.push('| ----------- | -------- |');
for (const r of uniqSort([...reqToJourneys.keys()])) {
	lines.push(`| ${r} | ${uniqSort([...reqToJourneys.get(r)!]).join(', ')} |`);
}
lines.push('');

lines.push('## Finding / decision → journeys');
lines.push('');
lines.push('| Finding / decision | Journeys |');
lines.push('| ------------------ | -------- |');
for (const f of uniqSort([...findingToJourneys.keys()])) {
	lines.push(`| ${f} | ${uniqSort([...findingToJourneys.get(f)!]).join(', ')} |`);
}
lines.push('');

lines.push('## Guard');
lines.push('');
if (guardHits.length) {
	lines.push('> ⚠️ Focused/skipped tests detected:');
	for (const h of guardHits) lines.push(`> - ${h}`);
} else {
	lines.push('No `test.only` / `test.skip` / `test.fixme` in `e2e/journeys` ✅');
}
lines.push('');

const rendered = lines.join('\n');

const check = process.argv.includes('--check');
if (check) {
	let current = '';
	try {
		current = readFileSync(OUT, 'utf8');
	} catch {
		/* missing */
	}
	if (current.trim() !== rendered.trim()) {
		console.error('e2e/COVERAGE.md is stale. Run `npm run coverage:map` and commit the result.');
		process.exit(1);
	}
	if (guardHits.length) {
		console.error('Focused/skipped tests present:\n' + guardHits.join('\n'));
		process.exit(1);
	}
	console.log('e2e/COVERAGE.md is up to date.');
} else {
	writeFileSync(OUT, rendered + '\n');
	console.log(
		`Wrote ${relative(ROOT, OUT)} (${specs.length} specs, ${allJourneys.size} journeys).`
	);
	if (guardHits.length) {
		console.error('Focused/skipped tests present:\n' + guardHits.join('\n'));
		process.exit(1);
	}
}
