/**
 * Database types
 *
 * This file will be auto-generated by kysely-codegen after migrations are run.
 * DO NOT EDIT MANUALLY
 *
 * To generate types, run: npm run db:types
 */

// Placeholder type until migration is run and types are generated
export interface DB {
	// Tables will be added here by kysely-codegen
}
