/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BlackoutDates {
  created_at: Generated<string>;
  date: string;
  id: string | null;
  reason: string | null;
}

export interface Clerkships {
  created_at: Generated<string>;
  description: string | null;
  id: string | null;
  name: string;
  required_days: number;
  specialty: string;
  updated_at: Generated<string>;
}

export interface PreceptorAvailability {
  created_at: Generated<string>;
  date: string;
  id: string | null;
  is_available: Generated<number>;
  preceptor_id: string;
  updated_at: Generated<string>;
}

export interface Preceptors {
  created_at: Generated<string>;
  email: string;
  id: string | null;
  max_students: Generated<number>;
  name: string;
  specialty: string;
  updated_at: Generated<string>;
}

export interface ScheduleAssignments {
  clerkship_id: string;
  created_at: Generated<string>;
  date: string;
  id: string | null;
  preceptor_id: string;
  status: Generated<string>;
  student_id: string;
  updated_at: Generated<string>;
}

export interface Students {
  created_at: Generated<string>;
  email: string;
  id: string | null;
  name: string;
  updated_at: Generated<string>;
}

export interface DB {
  blackout_dates: BlackoutDates;
  clerkships: Clerkships;
  preceptor_availability: PreceptorAvailability;
  preceptors: Preceptors;
  schedule_assignments: ScheduleAssignments;
  students: Students;
}
